version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/golang:1.9.2
        environment:
          HANAMI_ENV: test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/autopp/timegop

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            go get .

      # run unit tests
      - run:
          name: run unit tests
          command: ginkgo
